### ISSUE TITLE
Strip off json-rpc filter data

### ISSUE THREAD

**Issue by mkalinin** [ether-camp/ethereum-harmony#106]
Inner data that is kept for JSON-RPC filter purposes holds full block and transaction objects which is memory leak prone.
<img width="1150" alt="screen shot 2018-07-07 at 21 23 08" src="https://user-images.githubusercontent.com/1892772/42412322-fff7eb52-822b-11e8-8f1f-7d0d66711b1c.png">

**Comment by zilm13** [comment]
Should be fixed with https://github.com/ether-camp/ethereum-harmony/commit/63791f9f0e1c9fa4b860717533857302141fa104
Also I've checked all other listener through whole app, there are places where latest 100 blocks are kept, but it's guaranteed that there are no more than 100 of them, so as we keep latest 192 in memory anyway, I don't think it's an issue.
